Section "InputClass"
    Identifier      "x220 touchpad"
    MatchIsTouchpad "on"
    Driver          "libinput"
    Option "Tapping"            "on"
    Option "TappingButtonMap"   "lrm"
    Option "DisableWhileTyping" "on"
    Option "NaturalScrolling"   "false"
    Option "AccelSpeed"         "0.2"
EndSection

Section "InputClass"
    Identifier      "x220 trackpoint"
    MatchProduct    "TPPS/2 IBM TrackPoint"
    Driver          "libinput"
    Option "ScrollMethod" "button"
    Option "ScrollButton" "2"
    Option "AccelSpeed"   "0.3"
EndSection
