#!/bin/sh
# restore the wallpaper last chosen in azote (it saves ~/.fehbg), else the retro default
if [ -x "$HOME/.fehbg" ]; then
    "$HOME/.fehbg"
else
    feh --no-fehbg --bg-fill "$HOME/.local/share/backgrounds/retro-x220.png"
fi
