#!/usr/bin/env bash
. ~/.config/i3blocks/blocks/_lib
case $BTN in
    4) brightnessctl -q set 5%+ ;;
    5) brightnessctl -q -n2 set 5%- ;;
esac
pct=$(brightnessctl -m 2>/dev/null | awk -F, '{gsub("%","",$4); print $4}')
[[ -n $pct ]] && out "LCD" "$(printf '%02d' "$pct")%"
exit 0
